package com.hframework.web.config.bean;

import com.thoughtworks.xstream.annotations.XStreamAlias;
import com.thoughtworks.xstream.annotations.XStreamImplicit;

import java.util.ArrayList;
import java.util.List;
import com.thoughtworks.xstream.annotations.XStreamAsAttribute;
import com.hframework.web.config.bean.component.*;

/**
 * generated by hframework on 2016.
 */@XStreamAlias("component")
public class Component   {

	@XStreamImplicit
    @XStreamAlias("element")
	private List<Element> elementList;
	@XStreamAlias("baseEvents")
	private BaseEvents baseEvents;
	@XStreamAlias("events")
	private Events events;
	@XStreamAlias("example")
	private String example;
	@XStreamAsAttribute
    @XStreamAlias("id")
	private String id;
	@XStreamAsAttribute
    @XStreamAlias("init")
	private String init;
	@XStreamAsAttribute
    @XStreamAlias("type")
	private String type;
	@XStreamAsAttribute
    @XStreamAlias("data-set")
	private String dataSet;
	@XStreamAsAttribute
    @XStreamAlias("data-auth")
	private String dataAuth;

    @XStreamAsAttribute
    @XStreamAlias("path")
    private String path;

    public Component() {
    }
   
 	 	 
     public List<Element> getElementList(){
     	return elementList == null ? new ArrayList<Element>() : elementList;
     }

     public void setElementList(List<Element> elementList){
     	this.elementList = elementList;
     }
	 	 	 
     public BaseEvents getBaseEvents(){
     	return baseEvents == null ? new BaseEvents() : baseEvents;
     }

     public void setBaseEvents(BaseEvents baseEvents){
     	this.baseEvents = baseEvents;
     }
	 	 	 
     public Events getEvents(){
     	return events == null ? new Events() : events;
     }

     public void setEvents(Events events){
     	this.events = events;
     }
	 	 	 
     public String getExample(){
     	return example;
     }

     public void setExample(String example){
     	this.example = example;
     }
	 	 	 
     public String getId(){
     	return id;
     }

     public void setId(String id){
     	this.id = id;
     }
	 	 	 
     public String getInit(){
     	return init;
     }

     public void setInit(String init){
     	this.init = init;
     }
	 	 	 
     public String getType(){
     	return type;
     }

     public void setType(String type){
     	this.type = type;
     }
	 	 	 
     public String getDataSet(){
     	return dataSet;
     }

     public void setDataSet(String dataSet){
     	this.dataSet = dataSet;
     }
	 	 	 
     public String getDataAuth(){
     	return dataAuth;
     }

     public void setDataAuth(String dataAuth){
     	this.dataAuth = dataAuth;
     }

     public String getPath() {
      return path;
     }

     public void setPath(String path) {
      this.path = path;
     }
}
