package com.hframework.web.config.bean;

import com.thoughtworks.xstream.annotations.XStreamAlias;
import com.thoughtworks.xstream.annotations.XStreamImplicit;
import java.util.List;
import com.thoughtworks.xstream.annotations.XStreamAsAttribute;
import com.hframework.web.config.bean.module.*;

/**
 * generated by hframework on 2016.
 */@XStreamAlias("module")
public class Module   {

	@XStreamImplicit
    @XStreamAlias("page")
	private List<Page> pageList;
	@XStreamAsAttribute
    @XStreamAlias("code")
	private String code;
    @XStreamAsAttribute
    @XStreamAlias("is-extend")
    private String isExtend;


    public Module() {
    }
   
 	 	 
     public List<Page> getPageList(){
     	return pageList;
     }

     public void setPageList(List<Page> pageList){
     	this.pageList = pageList;
     }
	 	 	 
     public String getCode(){
     	return code;
     }

     public void setCode(String code){
     	this.code = code;
     }

    public String getIsExtend() {
        return isExtend;
    }

    public void setIsExtend(String isExtend) {
        this.isExtend = isExtend;
    }
}
