package com.hframework.web.config.bean.program;

import com.thoughtworks.xstream.annotations.XStreamAlias;

/**
 * generated by hframework on 2016.
 */@XStreamAlias("auth-instance")
public class AuthInstance {

    @XStreamAlias("user")
    private String user;
    @XStreamAlias("data")
    private String data;
    @XStreamAlias("role")
    private String role;
    @XStreamAlias("function")
    private String function;
    @XStreamAlias("dictionary")
    private String dictionary;
    @XStreamAlias("user-data-auth")
    private String userDataAuth;
    @XStreamAlias("user-func-auth")
    private String userFuncAuth;
    @XStreamAlias("super-auth-filter")
    private SuperAuthFilter superAuthFilter;



   public AuthInstance() {
      }

   public String getUser() {
    return user;
   }

   public void setUser(String user) {
    this.user = user;
   }

   public String getData() {
    return data;
   }

   public void setData(String data) {
    this.data = data;
   }

   public String getFunction() {
    return function;
   }

   public void setFunction(String function) {
    this.function = function;
   }

   public String getUserDataAuth() {
    return userDataAuth;
   }

   public void setUserDataAuth(String userDataAuth) {
    this.userDataAuth = userDataAuth;
   }

   public String getUserFuncAuth() {
    return userFuncAuth;
   }

   public void setUserFuncAuth(String userFuncAuth) {
    this.userFuncAuth = userFuncAuth;
   }

    public void setSuperAuthFilter(SuperAuthFilter superAuthFilter) {
        this.superAuthFilter = superAuthFilter;
    }

    public SuperAuthFilter getSuperAuthFilter() {
        if(superAuthFilter == null) superAuthFilter = new SuperAuthFilter();
        return superAuthFilter;
    }

    public String getRole() {
        return role;
    }

    public void setRole(String role) {
        this.role = role;
    }

    public String getDictionary() {
        return dictionary;
    }

    public void setDictionary(String dictionary) {
        this.dictionary = dictionary;
    }
}
