package com.hframework.web.config.bean.program;

import com.thoughtworks.xstream.annotations.XStreamAlias;
import com.thoughtworks.xstream.annotations.XStreamAsAttribute;

/**
 * generated by hframework on 2016.
 */@XStreamAlias("login")
public class Login {
    @XStreamAsAttribute
    @XStreamAlias("url")
    private String url;
    @XStreamAsAttribute
    @XStreamAlias("data-set")
    private String dataSet;

    public String getDataSet() {
        return dataSet;
    }

    public void setDataSet(String dataSet) {
        this.dataSet = dataSet;
    }

    public String getUrl() {
        return url;
    }

    public void setUrl(String url) {
        this.url = url;
    }
}
