package com.hframework.web.config.bean.program;

import com.thoughtworks.xstream.annotations.XStreamAlias;
import com.thoughtworks.xstream.annotations.XStreamImplicit;
import java.util.List;

/**
 * generated by hframework on 2016.
 */@XStreamAlias("modules")
public class Modules   {

	@XStreamImplicit
    @XStreamAlias("module")
	private List<Module> moduleList;

    public Modules() {
    }
   
 	 	 
     public List<Module> getModuleList(){
     	return moduleList;
     }

     public void setModuleList(List<Module> moduleList){
     	this.moduleList = moduleList;
     }
	 
}
