package com.hframework.web.config.bean.program;

import com.thoughtworks.xstream.annotations.XStreamAlias;

/**
 * generated by hframework on 2016.
 */@XStreamAlias("superManager")
public class SuperManager   {

	@XStreamAlias("code")
	private String code;
	@XStreamAlias("password")
	private String password;
	@XStreamAlias("name")
	private String name;

    public SuperManager() {
    }
   
 	 	 
     public String getCode(){
     	return code;
     }

     public void setCode(String code){
     	this.code = code;
     }
	 	 	 
     public String getPassword(){
     	return password;
     }

     public void setPassword(String password){
     	this.password = password;
     }
	 	 	 
     public String getName(){
     	return name;
     }

     public void setName(String name){
     	this.name = name;
     }
	 
}
