package com.hframework.web.config.bean.component;

import com.thoughtworks.xstream.annotations.XStreamAlias;
import com.thoughtworks.xstream.annotations.XStreamAsAttribute;
import com.thoughtworks.xstream.annotations.XStreamImplicit;

import java.util.List;

/**
 * generated by hframework on 2016.
 */@XStreamAlias("event")
public class Event   {

    @XStreamAlias("attach")
	private Attach attach;
    @XStreamAlias("source")
	private Source source;
    @XStreamImplicit
    @XStreamAlias("effect")
	private List<Effect> effectList;
    @XStreamImplicit
    @XStreamAlias("pre-handle")
    private List<PreHandle> preHandleList;
	@XStreamAsAttribute
    @XStreamAlias("id")
	private String id;
	@XStreamAsAttribute
    @XStreamAlias("type")
	private String type;
	@XStreamAsAttribute
    @XStreamAlias("name")
	private String name;
    @XStreamAsAttribute
    @XStreamAlias("description")
    private String description;
    @XStreamAsAttribute
    @XStreamAlias("rel")
    private String rel;
    public Event() {
    }


    public Attach getAttach() {
        return attach;
    }

    public void setAttach(Attach attach) {
        this.attach = attach;
    }

    public Source getSource() {
        return source == null ? new Source() : source;
    }

    public Source getSourceOrigin() {
        return source;
    }

    public void setSource(Source source) {
        this.source = source;
    }

    public List<Effect> getEffectList(){
     	return effectList;
     }

     public void setEffectList(List<Effect> effectList){
     	this.effectList = effectList;
     }
	 	 	 
     public String getId(){
     	return id;
     }

     public void setId(String id){
     	this.id = id;
     }
	 	 	 
     public String getType(){
     	return type;
     }

     public void setType(String type){
     	this.type = type;
     }
	 	 	 
     public String getName(){
     	return name;
     }

     public void setName(String name){
     	this.name = name;
     }

    public List<PreHandle> getPreHandleList() {
        return preHandleList;
    }

    public void setPreHandleList(List<PreHandle> preHandleList) {
        this.preHandleList = preHandleList;
    }

    public String getRel() {
        return rel;
    }

    public void setRel(String rel) {
        this.rel = rel;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }
}
