package com.hframework.web.config.bean.component;

import com.thoughtworks.xstream.annotations.XStreamAlias;
import com.thoughtworks.xstream.annotations.XStreamAsAttribute;

/**
 * generated by hframework on 2016.
 */@XStreamAlias("pre-handle")
public class PreHandle {

	@XStreamAsAttribute
    @XStreamAlias("case")
	private String case1;
	@XStreamAsAttribute
    @XStreamAlias("when")
	private String when;
	@XStreamAsAttribute
    @XStreamAlias("then")
	private String then;

    public PreHandle() {
    }

    public String getCase1() {
        return case1;
    }

    public void setCase1(String case1) {
        this.case1 = case1;
    }

    public String getWhen() {
        return when;
    }

    public void setWhen(String when) {
        this.when = when;
    }

    public String getThen() {
        return then;
    }

    public void setThen(String then) {
        this.then = then;
    }
}
