package com.hframework.web.config.bean.module;

import com.thoughtworks.xstream.annotations.XStreamAlias;
import com.thoughtworks.xstream.annotations.XStreamAsAttribute;

/**
 * generated by hframework on 2016.
 */@XStreamAlias("effect")
public class Effect   {

	@XStreamAsAttribute
    @XStreamAlias("type")
	private String type;
	@XStreamAsAttribute
    @XStreamAlias("param")
	private String param;
	@XStreamAsAttribute
    @XStreamAlias("action")
	private String action;

    public Effect() {
    }
   
 	 	 
     public String getType(){
     	return type;
     }

     public void setType(String type){
     	this.type = type;
     }
	 	 	 
     public String getParam(){
     	return param;
     }

     public void setParam(String param){
     	this.param = param;
     }
	 	 	 
     public String getAction(){
     	return action;
     }

     public void setAction(String action){
     	this.action = action;
     }
	 
}
