package com.hframework.web.config.bean.module;

import com.thoughtworks.xstream.annotations.XStreamAlias;
import com.thoughtworks.xstream.annotations.XStreamImplicit;
import java.util.List;
import com.thoughtworks.xstream.annotations.XStreamAsAttribute;

/**
 * generated by hframework on 2016.
 */@XStreamAlias("event")
public class Event   {

	@XStreamImplicit
    @XStreamAlias("attach")
	private List<Attach> attachList;
	@XStreamImplicit
    @XStreamAlias("source")
	private List<Source> sourceList;
	@XStreamImplicit
    @XStreamAlias("effect")
	private List<Effect> effectList;
	@XStreamAsAttribute
    @XStreamAlias("name")
	private String name;

    public Event() {
    }
   
 	 	 
     public List<Attach> getAttachList(){
     	return attachList;
     }

     public void setAttachList(List<Attach> attachList){
     	this.attachList = attachList;
     }
	 	 	 
     public List<Source> getSourceList(){
     	return sourceList;
     }

     public void setSourceList(List<Source> sourceList){
     	this.sourceList = sourceList;
     }
	 	 	 
     public List<Effect> getEffectList(){
     	return effectList;
     }

     public void setEffectList(List<Effect> effectList){
     	this.effectList = effectList;
     }
	 	 	 
     public String getName(){
     	return name;
     }

     public void setName(String name){
     	this.name = name;
     }
	 
}
