package com.hframework.web.config.bean.mapper;

import com.thoughtworks.xstream.annotations.XStreamAlias;
import com.thoughtworks.xstream.annotations.XStreamImplicit;

import java.util.ArrayList;
import java.util.List;

/**
 * generated by hframework on 2016.
 */@XStreamAlias("eventMapper")
public class EventMapper   {

	@XStreamImplicit
    @XStreamAlias("mapping")
	private List<Mapping> mappingList;

    public EventMapper() {
    }
   
 	 	 
     public List<Mapping> getMappingList(){
     	return mappingList == null ? new ArrayList<Mapping>() : mappingList;
     }

     public void setMappingList(List<Mapping> mappingList){
     	this.mappingList = mappingList;
     }
	 
}
