package com.hframework.web.config.bean.datasethelper;

import com.thoughtworks.xstream.annotations.XStreamAlias;
import com.thoughtworks.xstream.annotations.XStreamImplicit;
import java.util.List;

/**
 * generated by hframework on 2016.
 */@XStreamAlias("mappings")
public class Mappings   {

	@XStreamImplicit
    @XStreamAlias("mapping")
	private List<Mapping> mappingList;

    public Mappings() {
    }
   
 	 	 
     public List<Mapping> getMappingList(){
     	return mappingList;
     }

     public void setMappingList(List<Mapping> mappingList){
     	this.mappingList = mappingList;
     }
	 
}
