package com.hframework.web.config.bean.datasethelper;

import com.thoughtworks.xstream.annotations.XStreamAlias;
import com.thoughtworks.xstream.annotations.XStreamAsAttribute;

/**
 * generated by hframework on 2016.
 */@XStreamAlias("mapping")
public class Mapping   {

	@XStreamAsAttribute
    @XStreamAlias("help-dataset-field")
	private String helpDatasetField;
	@XStreamAsAttribute
    @XStreamAlias("effect-dataset-field")
	private String effectDatasetField;
    @XStreamAsAttribute
    @XStreamAlias("express")
    private String express;
    @XStreamAsAttribute
    @XStreamAlias("is-compare-key")
    private String isCompareKey;
    @XStreamAsAttribute
    @XStreamAlias("is-compare-name")
    private String isCompareName;

    public Mapping() {
    }
   
 	 	 
     public String getHelpDatasetField(){
     	return helpDatasetField;
     }

     public void setHelpDatasetField(String helpDatasetField){
     	this.helpDatasetField = helpDatasetField;
     }
	 	 	 
     public String getEffectDatasetField(){
     	return effectDatasetField;
     }

     public void setEffectDatasetField(String effectDatasetField){
     	this.effectDatasetField = effectDatasetField;
     }

    public String getExpress() {
        return express;
    }

    public void setExpress(String express) {
        this.express = express;
    }

    public String getIsCompareName() {
        return isCompareName;
    }

    public void setIsCompareName(String isCompareName) {
        this.isCompareName = isCompareName;
    }

    public String getIsCompareKey() {
        return isCompareKey;
    }

    public void setIsCompareKey(String isCompareKey) {
        this.isCompareKey = isCompareKey;
    }
}
